version: '3'

services:
   ftp:
      image: delfer/alpine-ftp-server
      platform: linux/x86_64
      ports:
        - "21:21"
      volumes:
        - ./ftp:/home/ftpusers
   apache:
    image: apache/superset
    ports:
      - "443:443"
    volumes:
      - ./webproject:/usr/local/apache2/htdocs
   db:
     image: mysql:5.7
     platform: linux/x86_64
     ports:
       - "543:543"
     socket: /var/run/mysqld/mysqld.sock
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     platform: linux/x86_64
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: